- package-lock.json
- views/layout.pug
The following was commented  in the layout.pug
include mixins/postlist
include mixins/contactform
Uncommented. Fixed.
> fixed posts_mixin_bug

- package-lock.json
- package.json
- routes/index.js
- views/courses.pug
- views/layout.pug
- views/mixins/courses.pug
- views/mixins/courses/coaching.pug
- views/mixins/courses/oneyear.pug
- views/mixins/courses/orientation.pug
- views/mixins/jumbotron.pug
- views/mixins/navigation.pug
1.New courses folder + 3 .pug files for 3 courses created
2. New courses.pug file, with "extends layout.pug" was created.
Currently there is no proper routing, since all 3 pages are visible on the courses.pug. In order to work on a specific template, you need to comments all courses, except that one, that you want to work on. 
((issue will be opened))
2. New routs for /courses in index.js - line 29
3. Updated one year courses html. To see the template use  this link: http://localhost:3000/courses
4. Added bootstrap +  "jquery to the json file, but still bootstrap is not working without cdn links in the layout.pug (issue will be opened)
> Courses branch | First page | One year course 

- assets/css/contactform.css
- assets/css/global.css
- helpers/passport.js
- public/scripts/frontend.js
- server.js
- views/layout.pug
- views/mixins/contactform.pug
1. Issue #50 
2. Issue #19 
3. Issue #17
> Small fixes

- server.js
The issues (#55 and #54 ) were fixed by changing the path to correct one.
> Fixes for #55 and #54

- assets/css/footer.css
- assets/css/oneyear.css
- views/layout.pug
- views/mixins/courses/oneyear.pug
Changed body in layout with data-spy.
Adding class to the oneyear course.
> Bug fixed #58

- assets/css/contactformfaded.css
- public/scripts/frontend.js
- views/index.pug
- views/layout.pug
- views/mixins/contactform.pug
- views/mixins/contactformfaded.pug
- views/mixins/landingpage/jumbotron.pug
> Added popup placeholder. 

- controllers/PagesController.js
- controllers/admin/AdminPagesController.js
- models/page.js
- routes/admin/pages.js
- routes/pages.js
- seeds.js
- server.js
- views/admin/editPage.pug
- views/admin/pages.pug
- views/layout.pug
- views/mixins/navigation.pug
- views/mixins/pagelist.pug
- views/page.pug
> pages entity

- views/admin/categories.pug
- views/admin/contacts.pug
- views/admin/editCategory.pug
- views/admin/editLocation.pug
- views/admin/editPage.pug
- views/admin/editStory.pug
- views/admin/locations.pug
- views/admin/pages.pug
- views/admin/stories.pug
- views/course.pug
- views/courses.pug
- views/events.pug
- views/index.pug
- views/layout.pug
- views/login.pug
- views/page.pug
- views/register.pug
- views/stories.pug
- views/story.pug
> added navigation to layout only removed from other mixins

- .env.example
- helper.js
- package-lock.json
- package.json
- server.js
you should install  all this package >>
sudo apt install redis
sudo apt-get install redis-server
npm install express-redis
npm i redis
sudo service redis restart
just for tomy >>
" sudo nano /etc/redis/redis.conf  "
> Cashing data with redis

- routes/index.js
- views/mixins/courses/singleCourse.pug
- views/mixins/navigation.pug
> issue #139 fixed. contact for is showed across the site

- assets/css/singleCourse.css
- controllers/JobsController.js
- package-lock.json
- routes/jobs.js
- server.js
- views/courses.pug
- views/jobsPublic.pug
- views/mixins/joblist.pug
- views/mixins/landingpage/getinvolved.pug
- views/mixins/landingpage/statsCounter.pug
- views/mixins/navigation.pug
Related to:
1. #136 
2. #149 
3. #151 
4. #152
> issues #136, 149, 151, 152

- assets/css/style.scss
- package-lock.json
- views/mixins/courses/singleCourse.pug
The pull request related to the #158.
Media breakpoints have been added.
The courses pages are responsive.
> Responsive courses page | issue#158

- assets/css/style.scss
- seeddata.js
- views/layout.pug
- views/mixins/singleStory.pug
- views/mixins/storylist.pug
- views/stories.pug
- views/story.pug
Hi Tommy, 
the idea for this section is when you click on the link "+show more" of the stories in the landing page, appears this page with the completed text of the student´s experience. So we need to connect "stories" in the main navigator with the section "stories on the landing page" and from there open this new page... Could be better if we create a pop window to read the complete experience... If you don't want at the moment create this pop-window, we should at least fix the links of the navigator to create a correct way to access the different part of the website.
So finally, this single-story section should show just one story and not all the stories... We need to delete the "each Loop"
> nice layout for single story view avatart

- assets/css/footer.scss
- assets/css/style.scss
- package-lock.json
- views/index.pug
- views/mixins/courses/singleCourse.pug
- views/mixins/landingpage/footer.pug
- views/mixins/landingpage/getinvolved.pug
- views/mixins/landingpage/ourCoursesSection.pug
- views/mixins/landingpage/partners.pug
- views/mixins/landingpage/statsCounter.pug
- views/mixins/landingpage/testimonialsDevugees.pug
- views/mixins/landingpage/upcomingEvents.pug
- views/mixins/navigation.pug
Footer responsive
Hamburger menu fix
> PR related to the #218

- assets/css/footer.scss
- assets/css/style.scss
- views/layout.pug
- views/mixins/landingpage/footer.pug
- views/mixins/landingpage/partners.pug
The style of the footer have been changed. 
Please review
> Changing footer style | issue #218

- views/mixins/landingpage/getinvolved.pug
- views/mixins/landingpage/home.pug
- views/mixins/landingpage/ourCoursesSection.pug
- views/mixins/landingpage/partners.pug
- views/mixins/landingpage/quote.pug
- views/mixins/landingpage/statsCounter.pug
- views/mixins/landingpage/testimonialsDevugees.pug
- views/mixins/landingpage/upcomingEvents.pug
Hover card effect on:
a) Our Courses
b) GET INVOLVED | created as our courses and events
c) STORIES
d) events: remove box shadow and keep it only on hover, like in our courses
e) Partners images are stored in media
f) stats counter animation
Unifying:
1. text font , weight and color
2. Buttons color and links color
3. events images size
> updating landing page | issue #223

- assets/css/style.scss
- assets/css/typography.scss
- controllers/EventsController.js
- controllers/admin/AdminCoursesController.js
- controllers/admin/AdminEventsController.js
- models/event.js
- routes/index.js
- views/admin/contacts.pug
- views/mixins/landingpage/testimonialsDevugees.pug
> visual changes landing page shadows, hover

- package-lock.json
- package.json
- server.js
- views/mixins/singleEvent.pug
Small edition to time in events cards.
Formatted with momentjs
> added formated time to events with moment

- controllers/EventsController.js
- views/mixins/eventlist.pug
PR related to #240 
EventsController.js has been modified.
Now each location returns 3 events per location.
Lopping through locations and comparing with events_id.
marketing-website/controllers/EventsController.js:7
> sort events by location

- .dockerignore
- Dockerfile
- README.md
- docker-compose.yml
- nginx/Dockerfile
- nginx/conf.d/default.conf
- nginx/nginx.conf
- package-lock.json
- package.json
> use docker as dev environment

- views/mixins/singleEvent.pug
> eventbrite redirection oncklick frorm events

- controllers/admin/AdminCoursesController.js
- controllers/admin/AdminStoriesController.js
- models/story.js
- seeddata.js
- seeds.js
- views/admin/editCourse.pug
- views/admin/editStory.pug
- views/mixins/singleStory.pug
- views/mixins/storyForm.pug
- views/story.pug
Closes #252 
Please check that upload functionality for stories works for avatar AND companylogo.
No design yet implemented.
> upload multiple images for story

- controllers/UserController.js
- server.js
Things to test:
- Login with wrong passsword = see flash
- Login with wrong user = see flash
- while logged out go to /admin/whatthefuck or /admin/stupidpath and got redirected to /users/login without  error
> show flash for invalid credentials, admin route fallback

- controllers/admin/AdminCoursesController.js
- formsConfig/courseFormConfig.js
- views/mixins/courseForm.pug
can you review the code, please!
> Course features 3 up to 5

- assets/css/style.scss
- controllers/UserController.js
- controllers/admin/AdminUsersController.js
- helpers/helper.js
- models/user.js
- routes/admin/users.js
- routes/users.js
- server.js
- views/admin/users.pug
- views/mixins/menuFooter.pug
> Superadmin activates user accounts

- helpers/helper.js
- routes/i18n.js
- server.js
Fix the localisation bug for browser with german as primary lang
> fix: localisation bug for german lang browsers

- controllers/UserController.js
> rebase reenable-register-backend-validation branch

- controllers/UserController.js
- package.json
- routes/users.js
- validation/users.js
> validate the register before submit show errors messages if there are

- assets/css/typography.scss
- controllers/IndexController.js
- controllers/admin/AdminEmployeesController.js
- controllers/admin/AdminLocationsController.js
- models/employee.js
- models/location.js
- routes/admin/locations.js
- views/contactLocations.pug
- views/mixins/employeeForm.pug
- views/mixins/locationForm.pug
contact person selectable from admin location form & automatically adds the contact person's phone number as the location phone number
> select contact person for locations

- assets/css/typography.scss
- controllers/admin/AdminCoursesController.js
- models/course.js
- views/mixins/courseForm.pug
- views/mixins/singleCourse.pug
Added to coursemodel: 
`computerKnowledge`, `education`, `requiredLanguages`, `other`, `financingoption`
> feat: enhance course model fields

- views/singleJob.pug
German is the language, Germany the country.
Germany's most [...] company
> suggestion to the genitive

- assets/css/global.scss
- assets/scripts/backend.js
- views/mixins/storyImages.pug
- views/mixins/successCarousel.pug
Change the primary color in the css.
Also in a couple of files where we apply inline css.
> Updating the primary color

- views/mixins/contactform.pug
> Require phone from contact us

- assets/css/style.scss
- assets/scripts/QuestionsDiagram.jsx
- assets/scripts/flow-builder.js
- controllers/admin/AdminQuestionsController.js
- package-lock.json
- package.json
- views/mixins/menuFooter.pug
FE:
- Contact-form question-steps have now slight y-transitions which is better for UX
BE: 
- Selection of nodes populates the correct input fields for update
- `Create new flow` creates now actually a new flow which can be directly used
- Improved order of fields/general UX
> Contactform: transitions, flow-builder improvements

- assets/scripts/QuestionsDiagram.jsx
- controllers/admin/AdminQuestionsController.js
- include also companyproperties for backend-check
- if just freeanswers, don't mark question as red
> Contactform / Flow builder improvements

- server.js
http://localhost:3000/de/courses/webentwickler-kurs
displays now correctly:
Webentwickler kurs - `Unsere Kurse` | Digital Career Institute
> title translates on sub-/ressources

- assets/scripts/QuestionsDiagram.jsx
- assets/scripts/flow-builder.js
- controllers/IndexController.js
- controllers/admin/AdminQuestionsController.js
- routes/admin/questions.js
- views/layout.pug
- request for all forms no matter where you are
- better tel input validation
- flowbuilder match answers to questions on hubspot
- just use contact fields for field matching
- adjust latency of neverbounce
> multistep-question-interview-improvements

- assets/scripts/QuestionsDiagram.jsx
- assets/scripts/flow-builder.js
- views/layout.pug
If you go to `https://staging.digitalcareerinstitute.org/jobcenter?last_touchpoint=test` the hidden form field `last_touchpoint` will prepopulated and also send to Hubspot
> Prepopulate hidden form field if query search param is present

- assets/scripts/flow-builder.js
- assets/scripts/frontend.js
- assets/scripts/helper.js
- controllers/IndexController.js
- views/layout.pug
- views/mixins/newsletter.pug
- use neverbounce not in development
- Handles and renders now proper json response
- If already subscribed or if successfully subscribed.
- Rudimentary translates response
> Newsletter signup responds with not nice message

- assets/scripts/QuestionsDiagram.jsx
- assets/scripts/flow-builder.js
- controllers/IndexController.js
If first request fails, dont use catch to finisih request - prefer finally statement
> Fix curriculum download is not triggering
